Rails/I18nLocaleTexts:
  Exclude:
    - app/controllers/account/**/*.rb

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - app/models/any_category.rb
    - app/models/consultation.rb
    - app/models/group.rb
    - app/models/page.rb
    - app/models/partner.rb
    - app/models/service.rb
    - app/models/testimonial.rb

Rails/InverseOf:
  Exclude:
    - app/models/user.rb
    - app/models/event.rb
    - app/models/event_category.rb
    - app/models/kid.rb
    - app/models/page.rb
    - app/models/post.rb
    - app/models/post_category.rb
    - app/models/provider.rb
    - app/models/provider_category.rb
    - app/models/provider_owner.rb

Rails/RedundantForeignKey:
  Exclude:
    - app/models/user.rb
    - app/models/event.rb
    - app/models/page.rb
    - app/models/provider.rb
    - app/models/provider_owner.rb

Lint/UnreachableCode:
  Exclude:
    - app/helpers/content_helper.rb

Rails/OutputSafety:
  Exclude:
    - app/components/filter_item_component.rb
    - app/helpers/app_ui_helper.rb
    - app/helpers/application_helper.rb
    - app/helpers/content_helper.rb
    - app/helpers/users_helper.rb

Rails/HasAndBelongsToMany:
  Exclude:
    - app/models/provider.rb
    - app/models/provider_category.rb
    - app/models/service.rb
    - app/models/subway_stop.rb
    - app/models/subdomain.rb
    - app/models/event.rb
    - app/models/language_info.rb
    - app/models/city.rb
    - app/models/country.rb




# TODO: missed rubocop configs

# #**********#####

# # This configuration was generated by
# # `rubocop --auto-gen-config`
# # on 2023-06-15 13:20:29 UTC using RuboCop version 1.52.0.
# # The point is for the user to remove these configuration records
# # one by one as the offenses are removed from the code base.
# # Note that changes in the inspected code, or installation of new
# # versions of RuboCop, may require this file to be generated again.

# # Offense count: 28
# # This cop supports unsafe autocorrection (--autocorrect-all).
# # Configuration parameters: Include, EnforcedStyle, NonImplicitAssociationMethodNames.
# # Include: spec/factories.rb, spec/factories/**/*.rb, features/support/factories/**/*.rb
# # SupportedStyles: explicit, implicit
# FactoryBot/AssociationStyle:
#   Exclude:
#     - 'spec/factories/cities.rb'
#     - 'spec/factories/events.rb'
#     - 'spec/factories/faqs.rb'
#     - 'spec/factories/favorites.rb'
#     - 'spec/factories/galleries.rb'
#     - 'spec/factories/language_infos.rb'
#     - 'spec/factories/locations.rb'
#     - 'spec/factories/page_group_items.rb'
#     - 'spec/factories/posts.rb'
#     - 'spec/factories/providers.rb'
#     - 'spec/factories/services.rb'
#     - 'spec/factories/videos.rb'
#     - 'spec/factories/viewed_contents.rb'
#     - 'spec/factories/views.rb'

# # Offense count: 9
# # This cop supports safe autocorrection (--autocorrect).
# # Configuration parameters: EnforcedStyle, ExplicitOnly.
# # SupportedStyles: require_parentheses, omit_parentheses
# FactoryBot/ConsistentParenthesesStyle:
#   Exclude:
#     - 'spec/models/location_spec.rb'
#     - 'spec/models/page_spec.rb'
#     - 'spec/models/post_spec.rb'
#     - 'spec/models/viewed_content_spec.rb'

# # Offense count: 1
# # This cop supports unsafe autocorrection (--autocorrect-all).
# # Configuration parameters: Include, EnforcedStyle, ExplicitOnly.
# # Include: **/*_spec.rb, **/spec/**/*, spec/factories.rb, spec/factories/**/*.rb, features/support/factories/**/*.rb
# # SupportedStyles: create_list, n_times
# FactoryBot/CreateList:
#   Exclude:
#     - 'spec/factories/providers.rb'

# # Offense count: 1
# FactoryBot/FactoryAssociationWithStrategy:
#   Exclude:
#     - 'spec/factories/kids.rb'

# # Offense count: 9
# # This cop supports safe autocorrection (--autocorrect).
# # Configuration parameters: Include.
# # Include: spec/factories.rb, spec/factories/**/*.rb, features/support/factories/**/*.rb
# FactoryBot/FactoryClassName:
#   Exclude:
#     - 'spec/factories/any_categories.rb'
#     - 'spec/factories/groups.rb'
#     - 'spec/factories/users.rb'

# # Offense count: 5
# # This cop supports safe autocorrection (--autocorrect).
# FactoryBot/RedundantFactoryOption:
#   Exclude:
#     - 'spec/factories/favorites.rb'
#     - 'spec/factories/page_group_items.rb'
#     - 'spec/factories/providers.rb'
#     - 'spec/factories/viewed_contents.rb'
#     - 'spec/factories/views.rb'

# # Offense count: 8
# # This cop supports unsafe autocorrection (--autocorrect-all).
# FactoryBot/SyntaxMethods:
#   Exclude:
#     - 'spec/mailers/provider_spec.rb'
#     - 'spec/mailers/user_spec.rb'

# # Offense count: 1
# Lint/UnreachableCode:
#   Exclude:
#     - 'app/helpers/content_helper.rb'

# # Offense count: 1
# # Configuration parameters: MinSize.
# Performance/CollectionLiteralInLoop:
#   Exclude:
#     - 'app/services/export/providers/full_export_service.rb'

# # Offense count: 4
# # This cop supports unsafe autocorrection (--autocorrect-all).
# Performance/MapCompact:
#   Exclude:
#     - 'app/services/export/providers/full_export_service.rb'

# # Offense count: 2
# # This cop supports safe autocorrection (--autocorrect).
# Performance/RedundantBlockCall:
#   Exclude:
#     - 'app/components/compare_table_component.rb'

# # Offense count: 2
# # This cop supports unsafe autocorrection (--autocorrect-all).
# Performance/StringInclude:
#   Exclude:
#     - 'app/controllers/concerns/i18n_ext.rb'
#     - 'app/helpers/banners_helper.rb'

# # Offense count: 1
# # This cop supports unsafe autocorrection (--autocorrect-all).
# Performance/TimesMap:
#   Exclude:
#     - 'spec/factories/posts.rb'

# # Offense count: 16
# # Configuration parameters: Include.
# # Include: app/models/**/*.rb
# Rails/HasAndBelongsToMany:
#   Exclude:
#     - 'app/models/city.rb'
#     - 'app/models/country.rb'
#     - 'app/models/event.rb'
#     - 'app/models/language_info.rb'
#     - 'app/models/provider.rb'
#     - 'app/models/provider_category.rb'
#     - 'app/models/service.rb'
#     - 'app/models/subdomain.rb'
#     - 'app/models/subway_stop.rb'

# # Offense count: 79
# Rails/I18nLocaleTexts:
#   Enabled: false

# # Offense count: 14
# # Configuration parameters: IgnoreScopes, Include.
# # Include: app/models/**/*.rb
# Rails/InverseOf:
#   Exclude:
#     - 'app/models/event.rb'
#     - 'app/models/event_category.rb'
#     - 'app/models/kid.rb'
#     - 'app/models/page.rb'
#     - 'app/models/post.rb'
#     - 'app/models/post_category.rb'
#     - 'app/models/provider.rb'
#     - 'app/models/provider_category.rb'
#     - 'app/models/provider_owner.rb'
#     - 'app/models/user.rb'

# # Offense count: 7
# Rails/OutputSafety:
#   Exclude:
#     - 'app/components/filter_item_component.rb'
#     - 'app/helpers/app_ui_helper.rb'
#     - 'app/helpers/application_helper.rb'
#     - 'app/helpers/content_helper.rb'
#     - 'app/helpers/users_helper.rb'

# # Offense count: 8
# # This cop supports safe autocorrection (--autocorrect).
# Rails/RedundantForeignKey:
#   Exclude:
#     - 'app/models/event.rb'
#     - 'app/models/page.rb'
#     - 'app/models/provider.rb'
#     - 'app/models/provider_owner.rb'
#     - 'app/models/user.rb'

# # Offense count: 6
# # Configuration parameters: Include.
# # Include: app/models/**/*.rb
# Rails/UniqueValidationWithoutIndex:
#   Exclude:
#     - 'app/models/any_category.rb'
#     - 'app/models/group.rb'
#     - 'app/models/page.rb'
#     - 'app/models/partner.rb'
#     - 'app/models/service.rb'
#     - 'app/models/testimonial.rb'
